language: objective-c

before_install:
  - pod repo add Cloudspace-iOS-Pods https://github.com/cloudspace/Cloudspace-iOS-PodSpecs
  - pod install
script:
  - xctool -workspace EasyReader.xcworkspace -scheme Development -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace EasyReader.xcworkspace -scheme Development -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
notifications:
  slack: cloudspace:euw2TezwiQfK9ebqBtGa1Rjz